collections:
  - name: community.postgresql
    source: https://galaxy.ansible.com
  - name: community.docker
    source: https://galaxy.ansible.com
  - name: ansible.windows
    source: https://galaxy.ansible.com
  - name: community.windows
    source: https://galaxy.ansible.com
